# Script for checking out sources and storing it as an artifact
# The artifact name is "modules"

jobs:
- job: xfel_modules
  pool:
    vmImage: ubuntu-18.04
  timeoutInMinutes: 120

  steps:

  # download sources
  - checkout: self
    path: ./modules/cctbx_project

  - script: |
      cd $(Pipeline.Workspace)
      ln -s modules/cctbx_project/libtbx/auto_build/bootstrap.py
    displayName: Link bootstrap.py

  - script: |
      cd $(Pipeline.Workspace)
      python bootstrap.py hot update --builder=xfel --python=38
      cd modules
      git clone https://github.com/nksauter/LS49.git
      git clone https://gitlab.com/cctbx/ls49_big_data.git
    displayName: Download sources

  - script: |
      cd $(Pipeline.Workspace)
      cd modules/uc_metrics
      git lfs install --local
      git lfs pull
      cd ../ls49_big_data
      git lfs install --local
      git lfs pull
    displayName: Download LFS files

  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(resources.pipeline.data_cache.projectID)'
      pipeline: '$(resources.pipeline.data_cache.pipelineID)'
      artifact: 'xfel_regression'
      path: $(Pipeline.Workspace)/modules/xfel_regression
    displayName: Download xfel_regression
    continueOnError: true

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: cci.lbl.gov,131.243.194.153 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAnPOtqyYASs6hc3fsmUQn92ovSozJsMsJyrMWjppUERX1tD4Fh0D7YaNhLvYpKi5mYVREo+tsKoOatCcqKGHCONWpzx7JHXUzfIBsy6nCeygRyyW4yuyoCuYFvOYLkaM4PrN/7XaZEnp1ux6/ZcbRxBDNK4f42svJUV39OX33tRuQWpP+O85paJr1ePHVz6U2n14a+3fRN3DBMti1dJuKOThU4djYEBQimx54pnW71eYORN2oUz+N/4RHAcomtxZpcUMl3Qadw8hD4s1XM6fzJ0Que7KefnnrPOgAEtZxKl9j09aaE70Oh+ie5Y6ckwddJ/4qZB5m2tBaEi3xuy0TSQ==
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7XgVgdU9GmZuo5yVyW/htrAuxe7ypuq7IowWwfUC0WZw9SPzQ8kOGj63plF3ytx/qpgvUlS1AiywO20rZ83gHmRdAiuvt9laH09KlWEUhIhAQTzesqBG5aUT0MKo01yxijoRl5HC8w/MdOanc0h01e6IxnZvgG0N30RB1i4xVPCtR/VBmXSp4R0T+Q/gJjfQssuBxHVMrrute4V3uUHek58FL2QgUB0+zq6ipETjuCJxTSyYVAFtCYDPYs+0lAYYkWrXALCr9kX9s22jYtkyv5kNw6mEW8nhtA7GbTdJLv4M6/WYtcvQV8TDcNCfltOfl81U3gcZ9zhQDKGVoNaJEw== buildbot@cci.lbl.gov
      sshKeySecureFile: id_rsa
    displayName: Download SSH key

  - script: |
      if [ ! -d "$(Pipeline.Workspace)/modules/xfel_regression" ]; then
        svn co svn+ssh://builder@cci.lbl.gov/xfel_regression/trunk $(Pipeline.Workspace)/modules/xfel_regression
      fi
      cd $(Pipeline.Workspace)/modules/xfel_regression
      svn update
    displayName: Update xfel_regression

  # preserve permissions and delete extra files
  - script: |
      cd $(Pipeline.Workspace)
      rm -fr modules/*/.git/*
      rm -fr modules/*/.svn/*
      rm -fr modules/*.tar
      tar -cf modules.tar modules
    displayName: Build tarball

  # publish artifact
  - publish: $(Pipeline.Workspace)/modules.tar
    artifact: xfel_modules
